# Generated by Django 3.0.3 on 2020-02-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200224_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title_en', models.CharField(blank=True, max_length=50)),
                ('title_fa', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, max_length=50)),
                ('name_fa', models.CharField(max_length=50)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('subteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='staff.Subteam')),
            ],
        ),

        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=50)),
                ('title_fa', models.CharField(max_length=50)),
            ],
        ),



        migrations.RemoveField(
            model_name='subsection',
            name='post',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subsection',
        ),
    ]
