# Generated by Django 3.0.3 on 2020-02-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200224_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=50)),
                ('title_fa', models.CharField(max_length=50)),
            ],
        ),


        migrations.AddField(
            model_name='subteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='staff.Team'),
        ),
    ]
