# Generated by Django 2.2.9 on 2020-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200224_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title_fa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
