# Generated by Django 2.2.9 on 2020-03-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20200224_1855'),
    ]

    operations = [
    ]
