# Generated by Django 2.2.9 on 2020-03-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200307_1358'),
    ]

    operations = [
    ]
