# Generated by Django 2.2.8 on 2019-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='participation.Badge'),
        ),
    ]
