# Generated by Django 2.2.8 on 2019-12-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_auto_20191227_1538'),
        ('participation', '0002_auto_20191228_1515'),
    ]

    operations = [
    ]
