# Generated by Django 2.2.8 on 2019-12-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_score'),
        ('participation', '0002_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='contest.Milestone')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='badges',
            field=models.ManyToManyField(related_name='teams', to='participation.Badge'),
        ),
    ]
