# Generated by Django 2.2.8 on 2020-01-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_auto_20200111_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='host',
        ),
        migrations.AddField(
            model_name='team',
            name='name_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
