# Generated by Django 2.2.8 on 2020-01-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0025_task_order'),
        ('participation', '0005_auto_20200131_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reciever',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recieved', to='participation.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='participation.Participant'),
            preserve_default=False,
        ),
    ]
