# Generated by Django 2.2.9 on 2020-02-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0007_auto_20200131_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sender',
        ),
        migrations.AddField(
            model_name='invitation',
            name='participant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='participation.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='participation.Team'),
            preserve_default=False,
        ),
    ]
