# Generated by Django 2.2.9 on 2020-02-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activateusertoken_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bmp',
            field=models.CharField(choices=[('BAC', 'Bacholar'), ('MAS', 'Master'), ('PHD', 'Ph.D')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.University'),
        ),
    ]
