# Generated by Django 2.2.9 on 2020-02-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200211_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
