# Generated by Django 2.2.8 on 2019-12-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_intro_term_of_use'),
        ('homepage', '0004_remove_timelineevent_order'),
    ]

    operations = [
    ]
