# Generated by Django 2.2.8 on 2019-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_merge_20191229_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
