# Generated by Django 2.2.9 on 2020-02-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_timelineevent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
