# Generated by Django 2.2.9 on 2020-02-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_count_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='query',
            new_name='evall',
        ),
    ]
