class ErrorMessages:
    ANSWER_NOT_STRING = "Answers should be string"
    ANSWER_STRING_MUST_BE_A_LIST = "This question answer should be list"
    SINGLE_ANSWER_ERROR = "Single answer should have only one answer, no more!"
    MULTI_ANSWER_LIMIT_REACHED_ERROR = "You should submit maximum of {0} answers for this question"
    ANSWER_TYPE_ERROR = "Answer type should be {0}"
    SINGLE_SELECT_ERROR = "You should choose only one answer"
    MULTI_SELECT_LIMIT_REACHED_ERROR = "You should select maximum of {0} answers for this question"
    INVALID_FILE_FORMAT = "File uploaded format is invalid, valid format is {0}"
    FILE_SIZE_LIMIT_EXCEEDED = "File size is too much, maximum file size is {0}"
    INVALID_LITERALS_FOR_NUMERIC_RANGE = "Entered range should contain numbers only"
    INVALID_NUMERIC_RANGE = "Entered range isn't a valid numeric range"
