# Generated by Django 2.2.8 on 2019-12-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('contest', '0002_auto_20191220_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to='question.Question'),
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to='contest.Trial'),
        ),
        migrations.AddField(
            model_name='questionrecipe',
            name='trial_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_recipes', to='contest.TrialRecipe'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contest.Contest'),
        ),
    ]
