# Generated by Django 2.2.8 on 2019-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20191223_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('scored', 'scored'), ('queued', 'queued'), ('judging', 'judging'), ('failed', 'failed'), ('error', 'error')], max_length=10)),
                ('info', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
