# Generated by Django 2.2.8 on 2019-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_score_question_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
