# Generated by Django 2.2.8 on 2019-12-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20191227_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='scoreboard_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoreboard_order_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
