# Generated by Django 2.2.8 on 2019-12-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20191227_1513'),
        ('contest', '0009_teamtask_final_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejudges', to='question.Question')),
            ],
        ),
    ]
