# Generated by Django 2.2.8 on 2019-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_rejudge'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejudge',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
