# Generated by Django 2.2.8 on 2020-01-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_rejudge_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scoring_type',
            field=models.CharField(choices=[('final_trial', 'final_trial'), ('weighted_average', 'weighted_average')], default='weighted_average', max_length=20),
        ),
    ]
