# Generated by Django 2.2.8 on 2020-01-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200104_1225'),
        ('contest', '0012_auto_20200103_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecipe',
            name='question_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_recipes', to='question.QuestionTag'),
        ),
    ]
