# Generated by Django 2.2.8 on 2020-01-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_questionrecipe_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
