# Generated by Django 2.2.8 on 2020-01-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20200107_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='file_answer',
        ),
    ]
