# Generated by Django 2.2.8 on 2020-01-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_questionsubmission_file_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='file_answer',
        ),
    ]
