# Generated by Django 2.2.8 on 2020-01-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_remove_questionsubmission_file_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='has_file',
            field=models.BooleanField(default=False),
        ),
    ]
