# Generated by Django 2.2.8 on 2020-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_questionsubmission_has_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
