# Generated by Django 2.2.8 on 2020-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20200110_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
