# Generated by Django 2.2.8 on 2020-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20200111_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
