# Generated by Django 2.2.8 on 2020-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_auto_20200111_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='trial_cooldown',
            field=models.FloatField(),
        ),
    ]
