# Generated by Django 2.2.8 on 2020-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0024_auto_20200125_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
