# Generated by Django 2.2.9 on 2020-02-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0026_auto_20200211_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trial_released',
            field=models.BooleanField(default=True),
        ),
    ]
