# Generated by Django 2.2.9 on 2020-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0027_task_trial_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='signup_open',
            field=models.BooleanField(default=True),
        ),
    ]
