# Generated by Django 2.2.9 on 2020-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_contest_signup_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submit_open',
            field=models.BooleanField(default=True),
        ),
    ]
