# Generated by Django 2.2.8 on 2020-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200110_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
