# Generated by Django 2.2.9 on 2020-02-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200110_1655'),
        ('blog', '0002_post_shown'),
    ]

    operations = [
    ]
