# Generated by Django 2.2.9 on 2020-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20200211_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_en',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
