# Generated by Django 2.2.8 on 2020-01-07 17:11

import apps.question.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_auto_20200107_1711'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_function', models.CharField(max_length=8000)),
                ('judge_function_name', models.CharField(default='function', max_length=150)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('single_answer', 'Single Answer'), ('multi_answer', 'Multi Answer'), ('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('file_upload', 'File Upload'), ('manual_judgment', 'Manual Judgment'), ('numeric_range', 'Numeric Range')], max_length=50)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_question.question_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('file_size_limit', models.IntegerField()),
                ('file_format', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='ManualJudgment',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='MultiAnswer',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('answer_count_limit', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('int', 'integer'), ('double', 'double'), ('text', 'text')], max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='NumericRange',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='Selective',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='SingleAnswer',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('answer_type', models.CharField(choices=[('int', 'integer'), ('double', 'double'), ('text', 'text')], max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='contest.Milestone')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.QuestionTag'),
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(on_delete=None, related_name='questions', to='contest.Task'),
        ),
        migrations.CreateModel(
            name='NeededFilesForQuestionJudgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=apps.question.models.NeededFilesForQuestionJudgment.upload_path)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='MultiSelect',
            fields=[
                ('selective_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Selective')),
                ('answer_count_limit', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.selective',),
        ),
        migrations.CreateModel(
            name='SingleSelect',
            fields=[
                ('selective_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Selective')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.selective',),
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('label', models.CharField(max_length=5)),
                ('selective_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.Selective')),
            ],
        ),
    ]
