# Generated by Django 2.2.8 on 2019-12-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeededFilesForQuestionJudgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgment_files', to='question.Question')),
            ],
        ),
    ]
