# Generated by Django 2.2.8 on 2019-12-27 13:11

import apps.question.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20191227_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededfilesforquestionjudgment',
            name='file',
            field=models.FileField(unique=True, upload_to=apps.question.models.NeededFilesForQuestionJudgment.upload_path),
        ),
    ]
