# Generated by Django 2.2.8 on 2019-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_neededfilesforquestionjudgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='judge_function',
            field=models.CharField(max_length=8000),
        ),
    ]
