# Generated by Django 2.2.8 on 2019-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20191227_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='judge_function_name',
            field=models.CharField(default='function', max_length=150),
        ),
    ]
