# Generated by Django 2.2.8 on 2019-12-27 14:59

import apps.question.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_judge_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededfilesforquestionjudgment',
            name='file',
            field=models.FileField(upload_to=apps.question.models.NeededFilesForQuestionJudgment.upload_path),
        ),
    ]
