# Generated by Django 2.2.9 on 2020-02-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200104_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='contest.Task'),
        ),
    ]
