# Generated by Django 2.2.9 on 2020-03-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0008_auto_20200202_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=128)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participation.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participation.Team')),
            ],
        ),
    ]
